### ISSUE TITLE
1.0.2 Exe Crashes at invocation 

### ISSUE THREAD

**Issue by mrg9999** [TechNGamer/CTT-Debloat.NET#1]
"A problem caused the program  to stop working correctly. Please close the program"
version 1.0.0 and 10.02

**Comment by mrg9999** [comment]
`Faulting application name: CTTDebloatNET.exe, version: 1.0.0.0, time stamp: 0x61933702
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1645, time stamp: 0x630193b4
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process ID: 0x3684
Faulting application start time: 0x01d8619a1daff31c
Faulting application path: C:\Downloads\CTT\CTTDebloatNET.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: a6e726df-ce36-4baf-9c1f-73085df8e7c3
Faulting package full name: 
Faulting package-relative application ID: 
Application: CTTDebloatNET-v1-0-0.exe

CoreCLR Version: 5.0.1321.56516
.NET Version: 5.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CTTDebloatNET.Program.Main(String[] args)


Application: CTTDebloatNET-1-0..2.exe
CoreCLR Version: 5.0.1321.56516
.NET Version: 5.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CTTDebloatNET.Program.Main(String[] args)
Faulting application name: CTTDebloatNET-1-0..2.exe, version: 1.0.0.0, time stamp: 0x61933702
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1645, time stamp: 0x630193b4
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process ID: 0x3a4c
Faulting application start time: 0x01d8619b358c19a8
Faulting application path: C:\Downloads\CTT\CTTDebloatNET-1-0..2.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 2efb43e7-9b34-4785-ab16-1f1a616f975e
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by TechNGamer** [comment]
What version of Windows you are running, ie, is it Windows 10 21H1 or Windows 11? Also, check to see that the path (which looks non-standard to me) have the correct permissions.
